import Head from 'next/head'
import Image from 'next/image'
import Slices from '../components/slices'

export default function Home() {
	return (
		<div>
			<Head>
				<title>Circle of Fifths</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<main>
				<h1>welcome to the circle of fifths</h1>
			</main>
			<Slices />
		</div>
	)
}
